spring:
  application:
    name: ZIPKIN-SERVER
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      read-timeout: 60
  tracing:
      enabled: true
      sampling:
        probability: 1.0
      propagation:
        type: b3