server:
  port: 8081

spring:
  application:
    name: EXAM-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_service
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508

openapi:
  service:
    title: Exam Service API Documentation
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /EXAM-SERVICE/v3/api-docs
  swagger-ui:
    path: /EXAM-SERVICE/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      read-timeout: 60
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3