server:
  port: 8084

spring:
  application:
    name: NOTIFICATION-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification_service
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    function:
      definition: consumerBinding;processorBinding;producerBinding
    stream:
      bindings:
        producerBinding-out-0:
          destination: processor-topic
        processorBinding-in-0:
          destination: processor-topic
        processorBinding-out-0:
          destination: consumer-topic
        consumerBinding-in-0:
          destination: consumer-topic
    kafka:
      binder:
        brokers:
          - localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      read-timeout: 60
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3