server:
  port: 8083

spring:
  application:
    name: SCHOOL-SERVICE
  data:
    mongodb:
      database: school_service
      port: 27017
      host: localhost
      auto-index-creation: true
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      read-timeout: 60
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3